protected call to source (.)

diff --git a/shed-container b/shed-container
--- a/shed-container
+++ b/shed-container
@@ -61,10 +61,9 @@ function strindex { # position of $2 in $1
 ########################################################################
 
 if [[ -e ./Shedfile ]]; then
-    bash -n ./Shedfile || fatal "Syntax error loading ./Shedfile"
     declare -a PROJECT BUILDS IMAGES CONTAINERS
     unset GROUPS; declare -A GROUPS
-    source ./Shedfile
+    source ./Shedfile || fatal "Syntax error loading ./Shedfile"
 fi
 
 ########################################################################
@@ -550,8 +549,8 @@ function container_build {
     local   -a  VOLUME
     local   -a  VOLUMES_FROM
 
-    bash -n $shedfile || fatal "Syntax error loading $shedfile"
-    source $shedfile    # source definitions
+    # source definitions
+    source $shedfile || fatal "Syntax error loading $shedfile"
 
     [[ -n $IMAGE ]] || fatal 'IMAGE must be defined'
 
diff --git a/shed-hub b/shed-hub
--- a/shed-hub
+++ b/shed-hub
@@ -54,17 +54,15 @@ function pager {        # colorized less
 ########################################################################
 
 if [[ -e ./Shedfile ]]; then
-    bash -n ./Shedfile || fatal "Syntax error loading ./Shedfile"
     declare -a PROJECT BUILDS IMAGES CONTAINERS
     unset GROUPS; declare -A GROUPS
-    source ./Shedfile
+    source ./Shedfile || fatal "Syntax error loading ./Shedfile"
 fi
 
 # can override TAGS_PREFIX
 for f in ${CONFIG[@]}; do
     [[ -e $f ]] || continue
-    bash -n $f || fatal "Syntax error loading $f"
-    source $f
+    source $f || fatal "Syntax error loading $f"
 done
 
 ########################################################################
