implemented dockerfile.shed

diff --git a/shed-hub b/shed-hub
--- a/shed-hub
+++ b/shed-hub
@@ -177,21 +177,21 @@ function help_command {
 
 # build [OPTIONS]
 function hub_build {
-    local opt quiet
-    local -i remove=0
+    local opt
+    local -i remove=0 quiet=0
 
     while getopts :hrq-: opt; do
         case $opt in
             r) remove=1 ;;
-            q) quiet='--quiet' ;;
+            q) quiet=1 ;;
             h) help_build ;;    
             -)  case $OPTARG in
                     remove) remove=1 ;;
                     remove=true) remove=1 ;;
                     remove=false) remove=0 ;;
-                    quiet) quiet='--quiet' ;;
-                    quiet=true) quiet='--quiet' ;;
-                    quiet=false) quiet='' ;;
+                    quiet) quiet=1 ;;
+                    quiet=true) quiet=1 ;;
+                    quiet=false) quiet=0 ;;
                     help) help_build ;;
                     *) help_build ;;
                 esac
@@ -243,6 +243,7 @@ function hub_build {
         fi
         # alternative name for dockerfile?
         local FILE=$image/Dockerfile    # default
+        # if tag has NAME with a # (NAME#DOCKERFILE)
         if [[ $image == *'#'* ]]; then
             IFS='#'
             set -- $image   # split on '#'
@@ -259,13 +260,81 @@ function hub_build {
         if [[ $image == . ]]; then name=${PWD##*/}; else name=$image; fi
         [[ -n $PROJECT && $PROJECT != $name ]] && name="${PROJECT}_$name"
 
+        # define more arguments to build
+        local       CGROUP_PARENT
+        local       CPUSET_CPUS
+        local       CPUSET_MEMS
+        local       CPU_PERIOD
+        local       CPU_QUOTA
+        local       CPU_SHARES
+        local       DISABLE_CONTENT_TRUST
+        local       FORCE_RM
+        local       ISOLATION
+        local       MEMORY
+        local       MEMORY_SWAP
+        local       NO_CACHE
+        local       PULL
+        local       QUIET
+        local       RM
+        local       SHM_SIZE
+        local   -a  BUILD_ARG
+        local   -a  TAG
+        local   -a  ULIMIT
+
+        local shedfile="${FILE}.shed"
+        # source definitions if available
+        if [[ -f $shedfile ]]; then
+            source $shedfile || fatal "Syntax error loading $shedfile"
+
+            [[ -n $CGROUP_PARENT ]] &&  CGROUP_PARENT="--cgroup-parent=$CGROUP_PARENT"
+            [[ -n $CPUSET_CPUS ]] &&    CPUSET_CPUS="--cpuset-cpus=$CPUSET_CPUS"
+            [[ -n $CPUSET_MEMS ]] &&    CPUSET_MEMS="--cpuset-mems=$CPUSET_MEMS"
+            [[ -n $CPU_PERIOD ]] &&     CPU_PERIOD="--cpu-period=$CPU_PERIOD"
+            [[ -n $CPU_QUOTA ]] &&      CPU_QUOTA="--cpu-quota=$CPU_QUOTA"
+            [[ -n $CPU_SHARES ]] &&     CPU_SHARES="--cpu-shares=$CPU_SHARES"
+            [[ -n $DISABLE_CONTENT_TRUST ]] && DISABLE_CONTENT_TRUST="--disable-content-trust=$DISABLE_CONTENT_TRUST"
+            [[ -n $FORCE_RM ]] &&       FORCE_RM="--force-rm=$FORCE_RM"
+            [[ -n $ISOLATION ]] &&      ISOLATION="--isolation=$ISOLATION"
+            [[ -n $MEMORY ]] &&         MEMORY="--memory=$MEMORY"
+            [[ -n $MEMORY_SWAP ]] &&    MEMORY_SWAP="--memory-swap=$MEMORY_SWAP"
+            [[ -n $NO_CACHE ]] &&       NO_CACHE="--no-cache=$NO_CACHE"
+            [[ -n $PULL ]] &&           PULL="--pull=$PULL"
+            [[ -n $RM ]] &&             RM="--rm=$RM"
+            [[ -n $SHM_SIZE ]] &&       SHM_SIZE="--shm-size=$SHM_SIZE"
+            [[ -n $QUIET ]] &&          QUIET="--quiet=$QUIET"
+
+            local -i i
+            for i in ${!BUILD_ARG[@]}; do   BUILD_ARG[i]="--build-arg=${BUILD_ARG[i]}"; done
+            for i in ${!TAG[@]}; do         TAG[i]="--tag=${TAG[i]}"; done
+            for i in ${!ULIMIT[@]}; do      ULIMIT[i]="--ulimit=${ULIMIT[i]}"; done
+        fi
+        (( quiet )) && QUIET="--quiet=true"    # override
+
         # build image
-        # TODO: define more arguments to build
         docker build \
-            $quiet \
             --file $FILE \
             --tag ${prefix}/${name}:${tag} \
+            $CGROUP_PARENT \
+            $CPUSET_CPUS \
+            $CPUSET_MEMS \
+            $CPU_PERIOD \
+            $CPU_QUOTA \
+            $CPU_SHARES \
+            $DISABLE_CONTENT_TRUST \
+            $FORCE_RM \
+            $ISOLATION \
+            $MEMORY \
+            $MEMORY_SWAP \
+            $NO_CACHE \
+            $PULL \
+            $QUIET \
+            $RM \
+            $SHM_SIZE \
+            ${BUILD_ARG[@]} \
+            ${TAG[@]} \
+            ${ULIMIT[@]} \
             $image
+
         # tag latest
         if [[ $tag != 'latest' ]]; then
             if docker history ${prefix}/${name}:latest &>/dev/null; then
@@ -300,7 +369,6 @@ Usage: $SELF build [OPTIONS]
 
 Build a project from the Shedfile source
 
-  --no-cache=false       Do not use cache when building the images
   -r, --remove=false     Remove containers, stopping if necessary
   -q, --quiet=false      Suppress the verbose output generated by the containers
 EOF
